version: '3.7'

services:

  phpmyadmin:
    container_name: phpmyadmin-joe1
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    ports:
      - 8081:80
  db:
    container_name: mysql-joe1
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: dupa
    ports:
      - "3307:3306"
    volumes:
      - db-vol:/var/lib/mysql

volumes:
  db-vol: